server:
  port: 8014
  address: 0.0.0.0
spring:
  application:
    name: joonbum

eureka:
  instance:
    prefer-ip-address: true
    hostname:
  client:
    register-with-eureka: true # ??? ???? (???) ?? ??
    fetch-registry: true
    serviceUrl:
      defaultZone: https://port-0-demo-32updzt2alpkqeavd.sel4.cloudtype.app/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"