server:
  port: 8014
spring:
  application:
    name: joonbum

eureka:
  instance:
    hostname: 18.116.248.2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
