server:
  port: 8012
  address: 0.0.0.0
spring:
  application:
    name: zuhee

eureka:
  instance:
    hostname: 3.143.74.33
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"