server:
  port: 8012
  address: 0.0.0.0
spring:
  application:
    name: zuhee

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # ??? ???? (???) ?? ??
    fetch-registry: true
    serviceUrl:
      defaultZone: https://port-0-test-cf24lcem0udh.gksl2.cloudtype.app/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"