server:
  port: 8761
spring:
  application:
    name: discovery_server

eureka:
  instance:
    hostname: 18.116.248.2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
