server:
  port: 8013
spring:
  application:
    name: dongjae

eureka:
  instance:

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.116.248.2:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

