server:
  port: 8013
  address: 0.0.0.0
spring:
  application:
    name: dongjae

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://3.143.74.33:8761/eureka


